import Link from "next/link";
import { notFound } from "next/navigation";
import { getEmailDetail } from "@/lib/dashboardData";
import { EventControls, TrackingToggle } from "./tracking-controls";

function date(value: string) { return new Intl.DateTimeFormat("en", { weekday: "short", month: "long", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)); }
function eventLabel(type: string) { return type === "click" ? "Clicked a link" : type === "open" ? "Opened your email" : "Loaded a mail preview"; }
function badge(confidence: number) { return confidence >= 85 ? "high" : confidence >= 55 ? "medium" : "low"; }

export default async function EmailDetailPage({ params }: PageProps<"/dashboard/sent/[id]">) {
  const { id } = await params; const detail = await getEmailDetail(id); if (!detail) notFound();
  const opens = detail.events.filter((event) => event.type === "open").length; const clicks = detail.events.filter((event) => event.type === "click").length;
  const clickByLink = new Map<string, number>(); detail.events.filter((event) => event.type === "click" && event.link_id).forEach((event) => clickByLink.set(event.link_id!, (clickByLink.get(event.link_id!) ?? 0) + 1));
  return <><header className="detail-header"><div><Link href="/dashboard/sent" className="back-link">← Sent emails</Link><p className="eyebrow">Email detail</p><h1>{detail.email.subject}</h1><p className="header-subtitle">Sent {date(detail.email.sent_at)} · {detail.email.recipient_count} recipient{detail.email.recipient_count === 1 ? "" : "s"}</p></div><TrackingToggle emailId={id} enabled={detail.email.tracking_enabled} /></header>
    <section className="metric-row detail-metrics"><article className="metric-card"><span>Opens</span><strong>{opens}</strong><small>Confirmed activity</small></article><article className="metric-card accent"><span>Clicks</span><strong>{clicks}</strong><small>Meaningful follow-through</small></article><article className="metric-card"><span>Links</span><strong>{detail.links.length}</strong><small>Tracked destinations</small></article></section>
    <section className="detail-grid"><article className="panel timeline-panel"><div className="panel-heading"><div><p className="eyebrow">Chronology</p><h2>Activity timeline</h2></div><span>{detail.events.length} events</span></div><div className="timeline">{detail.events.map((event) => <div className="timeline-event" key={event.id}><span className={`event-dot event-${event.type}`} /><div><strong>{eventLabel(event.type)}</strong><p>{date(event.at)} {event.is_proxy ? "· Proxy detected" : ""}{event.is_self ? "· Your device" : ""}</p></div><span className={`confidence ${badge(event.confidence)}`}>{event.confidence}% confidence</span></div>)}{detail.events.length === 0 && <div className="empty-state"><p>No activity yet. Trakk will label new opens and clicks here.</p></div>}</div></article>
      <aside className="panel links-breakdown"><div className="panel-heading"><div><p className="eyebrow">Destinations</p><h2>Link breakdown</h2></div></div>{detail.links.map((link) => <div className="tracked-link" key={link.id}><span className="link-index">{String(link.idx + 1).padStart(2, "0")}</span><div><a href={link.url} target="_blank" rel="noreferrer">{link.url}</a><small>{clickByLink.get(link.id) ?? 0} clicks</small></div></div>)}{detail.links.length === 0 && <div className="empty-state"><p>No links were tracked in this email.</p></div>}</aside></section>
    <section className="panel raw-log"><div className="panel-heading"><div><p className="eyebrow">Audit trail</p><h2>Raw event log</h2></div><span>Privacy-safe hashes only</span></div><div className="raw-events">{detail.events.map((event) => <div key={event.id}><code>{event.type}</code><time>{new Date(event.at).toISOString()}</time><span>{event.is_proxy ? "proxy" : "direct"}</span><EventControls eventId={event.id} /></div>)}{detail.events.length === 0 && <div className="empty-state"><p>There are no raw events to show.</p></div>}</div></section>
  </>;
}
